// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package net.sandipan.scalazmq.common.protos;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MarketDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string symbol = 1;
    /**
     * <code>required string symbol = 1;</code>
     */
    boolean hasSymbol();
    /**
     * <code>required string symbol = 1;</code>
     */
    java.lang.String getSymbol();
    /**
     * <code>required string symbol = 1;</code>
     */
    com.google.protobuf.ByteString
        getSymbolBytes();

    // required string bid = 2;
    /**
     * <code>required string bid = 2;</code>
     */
    boolean hasBid();
    /**
     * <code>required string bid = 2;</code>
     */
    java.lang.String getBid();
    /**
     * <code>required string bid = 2;</code>
     */
    com.google.protobuf.ByteString
        getBidBytes();

    // required string ask = 3;
    /**
     * <code>required string ask = 3;</code>
     */
    boolean hasAsk();
    /**
     * <code>required string ask = 3;</code>
     */
    java.lang.String getAsk();
    /**
     * <code>required string ask = 3;</code>
     */
    com.google.protobuf.ByteString
        getAskBytes();

    // required int32 volume = 4;
    /**
     * <code>required int32 volume = 4;</code>
     */
    boolean hasVolume();
    /**
     * <code>required int32 volume = 4;</code>
     */
    int getVolume();

    // required string timestamp = 5;
    /**
     * <code>required string timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required string timestamp = 5;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>required string timestamp = 5;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();
  }
  /**
   * Protobuf type {@code marketdata.MarketData}
   */
  public static final class MarketData extends
      com.google.protobuf.GeneratedMessage
      implements MarketDataOrBuilder {
    // Use MarketData.newBuilder() to construct.
    private MarketData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MarketData(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MarketData defaultInstance;
    public static MarketData getDefaultInstance() {
      return defaultInstance;
    }

    public MarketData getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MarketData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              symbol_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              bid_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              ask_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              volume_ = input.readInt32();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.sandipan.scalazmq.common.protos.Messages.internal_static_marketdata_MarketData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.sandipan.scalazmq.common.protos.Messages.internal_static_marketdata_MarketData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.sandipan.scalazmq.common.protos.Messages.MarketData.class, net.sandipan.scalazmq.common.protos.Messages.MarketData.Builder.class);
    }

    public static com.google.protobuf.Parser<MarketData> PARSER =
        new com.google.protobuf.AbstractParser<MarketData>() {
      public MarketData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MarketData(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MarketData> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string symbol = 1;
    public static final int SYMBOL_FIELD_NUMBER = 1;
    private java.lang.Object symbol_;
    /**
     * <code>required string symbol = 1;</code>
     */
    public boolean hasSymbol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string symbol = 1;</code>
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          symbol_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string symbol = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string bid = 2;
    public static final int BID_FIELD_NUMBER = 2;
    private java.lang.Object bid_;
    /**
     * <code>required string bid = 2;</code>
     */
    public boolean hasBid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string bid = 2;</code>
     */
    public java.lang.String getBid() {
      java.lang.Object ref = bid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bid = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBidBytes() {
      java.lang.Object ref = bid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string ask = 3;
    public static final int ASK_FIELD_NUMBER = 3;
    private java.lang.Object ask_;
    /**
     * <code>required string ask = 3;</code>
     */
    public boolean hasAsk() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string ask = 3;</code>
     */
    public java.lang.String getAsk() {
      java.lang.Object ref = ask_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ask_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ask = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAskBytes() {
      java.lang.Object ref = ask_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ask_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 volume = 4;
    public static final int VOLUME_FIELD_NUMBER = 4;
    private int volume_;
    /**
     * <code>required int32 volume = 4;</code>
     */
    public boolean hasVolume() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 volume = 4;</code>
     */
    public int getVolume() {
      return volume_;
    }

    // required string timestamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private java.lang.Object timestamp_;
    /**
     * <code>required string timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string timestamp = 5;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timestamp = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      symbol_ = "";
      bid_ = "";
      ask_ = "";
      volume_ = 0;
      timestamp_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSymbol()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAsk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVolume()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSymbolBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getAskBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, volume_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getTimestampBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSymbolBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getAskBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, volume_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getTimestampBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.sandipan.scalazmq.common.protos.Messages.MarketData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.sandipan.scalazmq.common.protos.Messages.MarketData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code marketdata.MarketData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements net.sandipan.scalazmq.common.protos.Messages.MarketDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.sandipan.scalazmq.common.protos.Messages.internal_static_marketdata_MarketData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.sandipan.scalazmq.common.protos.Messages.internal_static_marketdata_MarketData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.sandipan.scalazmq.common.protos.Messages.MarketData.class, net.sandipan.scalazmq.common.protos.Messages.MarketData.Builder.class);
      }

      // Construct using net.sandipan.scalazmq.common.protos.Messages.MarketData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        symbol_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        bid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ask_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        volume_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.sandipan.scalazmq.common.protos.Messages.internal_static_marketdata_MarketData_descriptor;
      }

      public net.sandipan.scalazmq.common.protos.Messages.MarketData getDefaultInstanceForType() {
        return net.sandipan.scalazmq.common.protos.Messages.MarketData.getDefaultInstance();
      }

      public net.sandipan.scalazmq.common.protos.Messages.MarketData build() {
        net.sandipan.scalazmq.common.protos.Messages.MarketData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.sandipan.scalazmq.common.protos.Messages.MarketData buildPartial() {
        net.sandipan.scalazmq.common.protos.Messages.MarketData result = new net.sandipan.scalazmq.common.protos.Messages.MarketData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.symbol_ = symbol_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bid_ = bid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ask_ = ask_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.volume_ = volume_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.sandipan.scalazmq.common.protos.Messages.MarketData) {
          return mergeFrom((net.sandipan.scalazmq.common.protos.Messages.MarketData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.sandipan.scalazmq.common.protos.Messages.MarketData other) {
        if (other == net.sandipan.scalazmq.common.protos.Messages.MarketData.getDefaultInstance()) return this;
        if (other.hasSymbol()) {
          bitField0_ |= 0x00000001;
          symbol_ = other.symbol_;
          onChanged();
        }
        if (other.hasBid()) {
          bitField0_ |= 0x00000002;
          bid_ = other.bid_;
          onChanged();
        }
        if (other.hasAsk()) {
          bitField0_ |= 0x00000004;
          ask_ = other.ask_;
          onChanged();
        }
        if (other.hasVolume()) {
          setVolume(other.getVolume());
        }
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000010;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSymbol()) {
          
          return false;
        }
        if (!hasBid()) {
          
          return false;
        }
        if (!hasAsk()) {
          
          return false;
        }
        if (!hasVolume()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.sandipan.scalazmq.common.protos.Messages.MarketData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.sandipan.scalazmq.common.protos.Messages.MarketData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string symbol = 1;
      private java.lang.Object symbol_ = "";
      /**
       * <code>required string symbol = 1;</code>
       */
      public boolean hasSymbol() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public java.lang.String getSymbol() {
        java.lang.Object ref = symbol_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          symbol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSymbolBytes() {
        java.lang.Object ref = symbol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          symbol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public Builder setSymbol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        symbol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public Builder clearSymbol() {
        bitField0_ = (bitField0_ & ~0x00000001);
        symbol_ = getDefaultInstance().getSymbol();
        onChanged();
        return this;
      }
      /**
       * <code>required string symbol = 1;</code>
       */
      public Builder setSymbolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        symbol_ = value;
        onChanged();
        return this;
      }

      // required string bid = 2;
      private java.lang.Object bid_ = "";
      /**
       * <code>required string bid = 2;</code>
       */
      public boolean hasBid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string bid = 2;</code>
       */
      public java.lang.String getBid() {
        java.lang.Object ref = bid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          bid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bid = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBidBytes() {
        java.lang.Object ref = bid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bid = 2;</code>
       */
      public Builder setBid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string bid = 2;</code>
       */
      public Builder clearBid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bid_ = getDefaultInstance().getBid();
        onChanged();
        return this;
      }
      /**
       * <code>required string bid = 2;</code>
       */
      public Builder setBidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bid_ = value;
        onChanged();
        return this;
      }

      // required string ask = 3;
      private java.lang.Object ask_ = "";
      /**
       * <code>required string ask = 3;</code>
       */
      public boolean hasAsk() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string ask = 3;</code>
       */
      public java.lang.String getAsk() {
        java.lang.Object ref = ask_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ask_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ask = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAskBytes() {
        java.lang.Object ref = ask_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ask_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ask = 3;</code>
       */
      public Builder setAsk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ask_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ask = 3;</code>
       */
      public Builder clearAsk() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ask_ = getDefaultInstance().getAsk();
        onChanged();
        return this;
      }
      /**
       * <code>required string ask = 3;</code>
       */
      public Builder setAskBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ask_ = value;
        onChanged();
        return this;
      }

      // required int32 volume = 4;
      private int volume_ ;
      /**
       * <code>required int32 volume = 4;</code>
       */
      public boolean hasVolume() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 volume = 4;</code>
       */
      public int getVolume() {
        return volume_;
      }
      /**
       * <code>required int32 volume = 4;</code>
       */
      public Builder setVolume(int value) {
        bitField0_ |= 0x00000008;
        volume_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 volume = 4;</code>
       */
      public Builder clearVolume() {
        bitField0_ = (bitField0_ & ~0x00000008);
        volume_ = 0;
        onChanged();
        return this;
      }

      // required string timestamp = 5;
      private java.lang.Object timestamp_ = "";
      /**
       * <code>required string timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string timestamp = 5;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timestamp = 5;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timestamp = 5;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 5;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:marketdata.MarketData)
    }

    static {
      defaultInstance = new MarketData(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:marketdata.MarketData)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_marketdata_MarketData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_marketdata_MarketData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\nmarketdata\"Y\n\nMarketDa" +
      "ta\022\016\n\006symbol\030\001 \002(\t\022\013\n\003bid\030\002 \002(\t\022\013\n\003ask\030\003" +
      " \002(\t\022\016\n\006volume\030\004 \002(\005\022\021\n\ttimestamp\030\005 \002(\tB" +
      "/\n#net.sandipan.scalazmq.common.protosB\010" +
      "Messages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_marketdata_MarketData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_marketdata_MarketData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_marketdata_MarketData_descriptor,
              new java.lang.String[] { "Symbol", "Bid", "Ask", "Volume", "Timestamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
